EVALUATE
{
	{	SUM( Sales[Quantity] )},			// computes the sum of all sales
	{	SUMX(Sales,Sales[Quantity] )},		// same thing
	{	SUMX(
			Sales,
			Sales[Quantity]*Sales[Net Price] 
		)},	// you have to use sumx if you use more than one column		
	{	[Sales Amount]	},					//  same as above in an explicit measure
	{	SUMX(
			Sales,
			Sales[Quantity]*RELATED('Product'[Unit Price] )
			 ) } 	// if one of the columns is from another table, use related to access its content
}